window.familyRecipes = [
  {
    "id": "air-fryer-hot-dogs",
    "title": "Air Fryer Hot Dogs",
    "category": "Sauce",
    "timeMinutes": 10,
    "servings": "Not listed",
    "source": "instagram.com",
    "tags": [
      "air fryer",
      "bowl",
      "sauce"
    ],
    "accent": "green",
    "intro": "Imported from instagram.com.",
    "ingredients": [
      "For the hot dogs:",
      "hot dogs",
      "hot dog buns",
      "chopped onion",
      "chopped gherkins",
      "mozzarella cheese",
      "For the sauce:",
      "1 tsp mustard",
      "1 tbsp ketchup",
      "1 1/2 tbsp mayonnaise"
    ],
    "steps": [
      "Add a layer of mozzarella cheese to each hot dog bun.",
      "Place a hot dog on top.",
      "In a bowl, mix the chopped onion and chopped gherkins.",
      "Add the mustard, ketchup, and mayonnaise.",
      "Mix well.",
      "Spoon the onion and gherkin mixture over the hot dogs.",
      "Top with more mozzarella cheese.",
      "Air fry at 200 C for 7-8 minutes, until hot and melted."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.instagram.com/p/DU3MFtOjCaU/"
  },
  {
    "id": "asian-beef-bowls",
    "title": "Asian Beef Bowls",
    "category": "Sauce",
    "timeMinutes": 12,
    "servings": "Not listed",
    "source": "recipetineats.com",
    "tags": [
      "beef",
      "bowl",
      "rice",
      "sauce"
    ],
    "accent": "tomato",
    "intro": "Imported from recipetineats.com.",
    "ingredients": [
      "For the sauce:",
      "1 tbsp hoisin sauce",
      "2 tbsp oyster sauce",
      "1 tbsp Chinese cooking wine, mirin, dry sherry, sake, or rice wine",
      "2 1/2 tbsp dark soy sauce",
      "2 tsp white sugar",
      "1/2 tsp sesame oil",
      "1/4 tsp white pepper or black pepper",
      "For the stir-fry:",
      "1 tbsp oil",
      "2 garlic cloves, minced",
      "1 small onion, finely chopped",
      "500 g ground beef",
      "1/2 cup scallions, sliced, plus more for garnish",
      "To garnish:",
      "sesame seeds",
      "cooked rice"
    ],
    "steps": [
      "Mix all sauce ingredients in a bowl.",
      "Heat the oil in a large skillet over high heat.",
      "Add the garlic and onion and cook for about 1 minute, until the onion starts to brown.",
      "Add the beef and cook, breaking it up as it browns.",
      "When the beef has changed from red to brown, add the sauce.",
      "Cook for another 2 minutes, until the sauce has mostly evaporated and the beef is cooked.",
      "Stir through the scallions.",
      "Serve over rice, garnished with more scallions and sesame seeds."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.recipetineats.com/asian-beef-bowls/"
  },
  {
    "id": "authentic-hungarian-goulash",
    "title": "Authentic Hungarian Goulash",
    "category": "Baking",
    "timeMinutes": 70,
    "servings": "Not listed",
    "source": "daringgourmet.com",
    "tags": [
      "beef",
      "goulash",
      "pork",
      "potato"
    ],
    "accent": "yellow",
    "intro": "Imported from daringgourmet.com.",
    "ingredients": [
      "For the goulash:",
      "3 tbsp pork lard, butter, or bacon grease",
      "1 1/2 lb yellow onions, chopped",
      "1/4 cup Hungarian sweet paprika",
      "1 1/2 lb stewing beef, cut into 1/2-inch pieces",
      "5 cloves garlic, minced",
      "2 red bell peppers, cut into 1/2-inch chunks",
      "1 yellow bell pepper, cut into 1/2-inch chunks",
      "2 tomatoes, diced",
      "2 carrots, diced",
      "2 medium potatoes, cut into 1/2-inch chunks",
      "5 cups beef broth",
      "1 bay leaf",
      "1 tsp salt",
      "1/2 tsp freshly ground black pepper",
      "1/2 tsp crushed caraway seeds, optional"
    ],
    "steps": [
      "Melt the lard in a Dutch oven over medium-high heat.",
      "Cook the onions until they begin to brown, about 7-10 minutes.",
      "Add the beef and cook until it just starts to brown, about 7-10 minutes.",
      "Add the bell peppers, tomatoes, and garlic.",
      "Cook for another 6-8 minutes.",
      "Remove the pot from the heat.",
      "Stir in the paprika, salt, pepper, and caraway if using.",
      "Add the beef broth and bay leaf.",
      "Return to the stove and bring to a boil.",
      "Reduce the heat to medium-low, cover, and simmer for 40 minutes.",
      "Add the carrots and potatoes.",
      "Return to a boil, reduce the heat again, cover, and simmer until the beef is tender, about 30-40 minutes.",
      "Adjust salt to taste and remove the bay leaf.",
      "Serve with crusty bread and sour cream if desired."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.daringgourmet.com/traditional-hungarian-goulash-gulyas/"
  },
  {
    "id": "bibimbap",
    "title": "Bibimbap",
    "category": "Sauce",
    "timeMinutes": 10,
    "servings": "Not listed",
    "source": "instagram.com",
    "tags": [
      "beef",
      "bowl",
      "rice",
      "sauce",
      "vegetable"
    ],
    "accent": "blue",
    "intro": "Imported from instagram.com.",
    "ingredients": [
      "For the beef:",
      "400 g beef mince",
      "2 cloves garlic, grated",
      "2 tbsp soy sauce",
      "2 tbsp brown sugar",
      "For the vegetables:",
      "6-8 dried shiitake mushrooms, soaked in hot water for 10 minutes",
      "3-4 tbsp reserved shiitake soaking liquid",
      "1 large carrot, julienned",
      "1/2 cucumber or 160 g cucumber, thinly sliced",
      "1 tsp sesame oil",
      "3 tbsp oil, divided",
      "3/4 tsp salt, divided",
      "1 tbsp soy sauce",
      "1 tbsp brown sugar",
      "For the hot chili sauce:",
      "2 tbsp gochujang",
      "2 tbsp white sugar",
      "2 tbsp hot water",
      "2 tsp sesame oil",
      "1 tsp soy sauce",
      "2 tsp toasted white sesame seeds",
      "To serve:",
      "3-4 bowls cooked rice",
      "3-4 eggs",
      "kimchi",
      "Korean seaweed flakes, optional"
    ],
    "steps": [
      "In a bowl, marinate the beef mince with grated garlic, 2 tbsp soy sauce, and 2 tbsp brown sugar.",
      "Mix well and set aside.",
      "Sprinkle 1/2 tsp salt over the cucumber slices and toss well.",
      "Let the cucumber sit for 10 minutes.",
      "Rinse under cold water and gently squeeze out excess moisture.",
      "Heat 1 tsp sesame oil in a frying pan over medium-high heat.",
      "Stir-fry the carrots with a pinch of salt for 2-3 minutes.",
      "Remove the carrots and set aside.",
      "Squeeze excess water from the soaked shiitake mushrooms and slice thinly.",
      "Heat 1 tbsp oil in a pan and stir-fry the mushrooms for 3-4 minutes.",
      "Add 1 tbsp brown sugar, 1 tbsp soy sauce, and 3-4 tbsp shiitake soaking liquid.",
      "Stir-fry for another minute.",
      "Taste and adjust with more soy sauce or sugar if needed.",
      "Set the mushrooms aside.",
      "Heat 2 tbsp oil in a frying pan.",
      "Cook the marinated beef over medium heat for 5-6 minutes, until browned and cooked through.",
      "Remove the beef from the heat and set aside.",
      "Cook the eggs sunny-side up in a lightly oiled pan.",
      "In a small bowl, whisk together the gochujang, sugar, hot water, sesame oil, soy sauce, and sesame seeds until smooth.",
      "Place hot rice in each bowl.",
      "Arrange the cooked beef, shiitake mushrooms, carrots, and cucumber on top.",
      "Add a fried egg in the center.",
      "Drizzle with chili sauce.",
      "Garnish with kimchi and Korean seaweed flakes if desired."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.instagram.com/p/DTzcheSkvhP/"
  },
  {
    "id": "cabbage-soup",
    "title": "Cabbage Soup",
    "category": "Baking",
    "timeMinutes": 55,
    "servings": "Not listed",
    "source": "themediterraneandish.com",
    "tags": [
      "cabbage",
      "soup",
      "vegetable"
    ],
    "accent": "purple",
    "intro": "Imported from themediterraneandish.com.",
    "ingredients": [
      "For the soup:",
      "2 tbsp extra virgin olive oil",
      "1 medium yellow onion, chopped",
      "3 garlic cloves, minced",
      "1 medium head green cabbage, cored and chopped",
      "2 celery sticks, chopped",
      "2 carrots, sliced into thin rounds",
      "kosher salt",
      "black pepper",
      "1/2 tsp ground turmeric",
      "1 tsp ground cumin",
      "1 tsp ground coriander",
      "1/2-1 tsp Aleppo pepper or red pepper flakes",
      "1 28-oz can diced tomatoes",
      "3 cups low-sodium vegetable broth",
      "1 cup chopped parsley leaves",
      "3 green onions, sliced",
      "1-inch piece fresh ginger, peeled and finely grated",
      "1 large lemon, zested and juiced"
    ],
    "steps": [
      "Heat the olive oil in a large Dutch oven until shimmering.",
      "Add the onion and garlic and cook until fragrant.",
      "Add the cabbage, celery, carrots, salt, and pepper.",
      "Cook, stirring occasionally, until the vegetables soften, about 5-7 minutes.",
      "Stir in the turmeric, cumin, coriander, and Aleppo pepper.",
      "Add the diced tomatoes with their juices and the vegetable broth.",
      "Bring to a boil for about 5 minutes.",
      "Lower the heat to medium-low, partially cover, and simmer until the vegetables are tender, about 20-25 minutes.",
      "Turn off the heat.",
      "Stir in the parsley, green onions, ginger, lemon zest, and lemon juice.",
      "Taste and adjust seasoning."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.themediterraneandish.com/cabbage-soup/"
  },
  {
    "id": "cheesy-ground-beef-quesadillas",
    "title": "Cheesy Ground Beef Quesadillas",
    "category": "Dinner",
    "timeMinutes": 35,
    "servings": "Not listed",
    "source": "girlheartfood.com",
    "tags": [
      "beef",
      "bowl",
      "vegetable"
    ],
    "accent": "red",
    "intro": "Imported from girlheartfood.com.",
    "ingredients": [
      "For the quesadillas:",
      "1/2 tbsp olive oil",
      "1 lb ground beef",
      "1 tsp chili powder",
      "1 tsp ground chipotle chili pepper",
      "1/2 tsp dried oregano",
      "1/2 tsp ground cumin",
      "1/2 tsp garlic powder",
      "1/2 tsp onion powder",
      "1/2 tsp salt",
      "1/2 tsp freshly ground black pepper",
      "1/4 tsp ground cayenne pepper",
      "1 tbsp tomato paste",
      "2 tbsp unsalted beef stock or broth",
      "12 oz shredded cheese blend, divided",
      "6 flour tortillas, 7-8 inches each",
      "2 tbsp vegetable oil, for the pan",
      "salsa",
      "guacamole",
      "sour cream"
    ],
    "steps": [
      "Heat the oven to 200 F so cooked quesadillas can stay warm.",
      "Heat the olive oil in a large nonstick pan over medium heat.",
      "Add the beef, chili powder, chipotle, oregano, cumin, garlic powder, onion powder, salt, black pepper, and cayenne.",
      "Cook, breaking up the beef, until browned and cooked through, about 8-10 minutes.",
      "Stir in the tomato paste and beef stock and cook for 1-2 minutes more.",
      "Transfer the beef to a bowl and drain excess grease if needed.",
      "Divide about 8 oz cheese among one side of the tortillas.",
      "Add the beef over the cheese, then top with the remaining 4 oz cheese.",
      "Fold each tortilla into a half moon.",
      "Wipe out the pan if needed.",
      "Heat about 2 tsp vegetable oil over medium-low heat.",
      "Cook 2 quesadillas at a time for about 2 minutes per side, until golden, crisp, and melted inside.",
      "Move cooked quesadillas to the warm oven while you cook the rest.",
      "Cut each quesadilla in half and serve with salsa, guacamole, or sour cream."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://girlheartfood.com/cheesy-ground-beef-quesadillas/"
  },
  {
    "id": "chicken-fajita-bowls",
    "title": "Chicken Fajita Bowls",
    "category": "Dinner",
    "timeMinutes": 30,
    "servings": "Not listed",
    "source": "thedizzycook.com",
    "tags": [
      "h-ingredients",
      "bean",
      "bowl",
      "cauliflower",
      "chicken"
    ],
    "accent": "green",
    "intro": "Imported from thedizzycook.com.",
    "ingredients": [
      "For the spice mixture:",
      "2 tsp chili powder",
      "1 1/2 tsp cumin",
      "1 tsp smoked paprika",
      "1 tsp garlic powder",
      "1 tsp kosher salt",
      "For the fajitas:",
      "3 tsp olive oil, divided",
      "1 red bell pepper, sliced into strips",
      "1 orange or yellow bell pepper, sliced into strips",
      "3 large shallots or 1 large yellow onion, sliced into strips",
      "2 lb skinless chicken breasts, sliced into thin 2-3 inch strips",
      "2 tbsp coconut aminos",
      "kosher salt",
      "black pepper",
      "For the bowls:",
      "1 15 oz can black beans, rinsed and drained",
      "3 cups romaine lettuce, chopped",
      "2/3 cup frozen corn",
      "10 oz white rice or cauliflower rice",
      "avocado, optional",
      "sour cream, optional",
      "cilantro, optional"
    ],
    "steps": [
      "Stir together the chili powder, cumin, smoked paprika, garlic powder, and salt in a small bowl.",
      "Heat 2 tsp olive oil in a large cast iron pan over medium-high heat.",
      "Add the shallots or onion and bell peppers in a single layer.",
      "Season with salt and pepper.",
      "Let them cook undisturbed for about 5 minutes to get some char.",
      "Stir as needed and continue cooking until softened, about 10-15 minutes.",
      "Remove the vegetables from the pan or push them to the side if there is room.",
      "Add the remaining 1 tsp olive oil over medium-high heat.",
      "Add the sliced chicken in a single layer.",
      "Let the chicken brown for 2-3 minutes.",
      "Stir and cook for another 2-3 minutes, until almost cooked through.",
      "Stir in the spice mixture until the chicken is well coated.",
      "Add the coconut aminos and stir while they sizzle.",
      "Remove the chicken from the pan.",
      "Lower the heat to medium and add the frozen corn.",
      "Cook just until warmed through.",
      "Return the chicken, vegetables, and corn to the pan and stir together, or keep them separate for serving.",
      "Build bowls with rice, black beans, chicken, vegetables, corn, and romaine.",
      "Top with avocado, cilantro, and sour cream if using."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://thedizzycook.com/chicken-fajita-bowls/?utm_source=convertkit&utm_medium=email&utm_campaign=Easy+Meal+Prep+Weekly+Meal+Plan+++Grocery+List+Done+For+You+%285%2F9%29+-+21695118#h-ingredients"
  },
  {
    "id": "chicken-pesto-pasta",
    "title": "Chicken Pesto Pasta",
    "category": "Baking",
    "timeMinutes": 20,
    "servings": "Not listed",
    "source": "themediterraneandish.com",
    "tags": [
      "wprm-recipe-container-72310",
      "chicken",
      "pasta",
      "pesto",
      "sauce"
    ],
    "accent": "tomato",
    "intro": "Imported from themediterraneandish.com.",
    "ingredients": [
      "For the pasta:",
      "1 lb boneless skinless chicken breasts, cut into 1-inch pieces",
      "1 tsp Italian seasoning",
      "kosher salt",
      "black pepper",
      "8 oz penne pasta",
      "2 tbsp extra virgin olive oil",
      "1/2 cup heavy cream",
      "1/4 cup parmesan cheese, plus more for serving",
      "1/4 cup sun-dried tomatoes, drained if packed in oil",
      "1/2 cup basil pesto",
      "1/2-1 tsp red pepper flakes",
      "torn basil leaves, for garnish"
    ],
    "steps": [
      "Season the chicken with Italian seasoning and a generous pinch each of salt and pepper.",
      "Bring a pot of water to a boil and salt it well.",
      "Cook the penne until al dente according to the package, about 8-9 minutes.",
      "Meanwhile, heat the olive oil in a large nonstick skillet over medium-high heat.",
      "Cook the chicken, tossing occasionally, until golden outside and cooked through, about 7-8 minutes.",
      "Reserve about 1 cup pasta water, then drain the pasta.",
      "Lower the heat under the chicken.",
      "Stir in the pasta, heavy cream, parmesan, and sun-dried tomatoes.",
      "Add reserved pasta water a few tbsp at a time if the sauce needs loosening.",
      "Remove the pan from the heat.",
      "Stir in the pesto.",
      "Finish with more parmesan, red pepper flakes, and torn basil leaves."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.themediterraneandish.com/creamy-chicken-pesto-pasta/#wprm-recipe-container-72310"
  },
  {
    "id": "chicken-stroganoff",
    "title": "Chicken Stroganoff",
    "category": "Sauce",
    "timeMinutes": 60,
    "servings": "Not listed",
    "source": "norecipes.com",
    "tags": [
      "bowl",
      "chicken",
      "rice",
      "sauce"
    ],
    "accent": "yellow",
    "intro": "Imported from norecipes.com.",
    "ingredients": [
      "For the stroganoff:",
      "400 g boneless skinless chicken thighs",
      "salt",
      "black pepper",
      "2 tbsp all-purpose flour",
      "1 tbsp cultured unsalted butter",
      "250 g button mushrooms, sliced 1/4-inch thick",
      "175 g onions, finely diced",
      "1/4 cup dry vermouth",
      "1 cup low-sodium chicken stock",
      "1 tbsp tomato paste",
      "1 bay leaf",
      "5 sprigs fresh thyme, tied with twine",
      "1/3 cup sour cream"
    ],
    "steps": [
      "Season the chicken generously with salt and pepper, then dust with flour.",
      "Heat a frying pan over medium-high heat and melt the butter.",
      "Add the chicken in a single layer.",
      "Brown one side without moving it, about 5 minutes.",
      "Flip and brown the other side.",
      "Transfer the chicken to a bowl.",
      "Add the mushrooms to the pan in a single layer.",
      "Brown one side, then the other, waiting for released liquid to evaporate.",
      "Add the onions and saute until the mushrooms and onions are well browned, about 10 minutes more.",
      "Deglaze with vermouth and boil until most of the liquid is gone.",
      "Add the chicken stock, tomato paste, bay leaf, and thyme.",
      "Return the chicken to the pan.",
      "Cover and simmer over medium-low heat for 10 minutes.",
      "Uncover and simmer about 10 minutes more, until the chicken is tender and the sauce is thick.",
      "Temper the sour cream with a few spoonfuls of hot sauce from the pan.",
      "Stir the sour cream mixture back into the pan.",
      "Adjust salt and serve with buttered egg noodles or rice."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://norecipes.com/chicken-stroganoff-recipe/#recipe"
  },
  {
    "id": "cold-roast-beef-salad",
    "title": "Cold Roast Beef Salad",
    "category": "Salad",
    "timeMinutes": 15,
    "servings": "Not listed",
    "source": "garlicandzest.com",
    "tags": [
      "beef",
      "bowl",
      "dressing",
      "salad"
    ],
    "accent": "blue",
    "intro": "Duplicate link: https://www.garlicandzest.com/cold-roast-beef-salad/#recipe",
    "ingredients": [
      "For the salad:",
      "4 cups arugula",
      "1 cup Brussels sprouts, thinly sliced",
      "1/2 cup frozen peas, thawed",
      "1/4 cup red onion, thinly sliced",
      "1 cup cherry or grape tomatoes, halved",
      "1/3 cup pitted kalamata olives, halved",
      "1 cup ciliegine, halved, or diced fresh mozzarella",
      "1/3 lb very thinly sliced leftover roast beef",
      "2 tbsp shaved Parmigiano Reggiano or Grana Padano",
      "For the dressing:",
      "1 large garlic clove, minced",
      "1 tsp Dijon mustard",
      "1/2 tsp lemon zest",
      "1 1/2 tbsp lemon juice",
      "2 tbsp olive oil",
      "2 tbsp sun-dried tomatoes in oil, finely minced",
      "1 tbsp oil from the sun-dried tomatoes",
      "pinch kosher salt",
      "pinch black pepper"
    ],
    "steps": [
      "Whisk together the garlic, Dijon, lemon zest, lemon juice, olive oil, sun-dried tomatoes, sun-dried tomato oil, salt, and pepper.",
      "Toss the arugula and shaved Brussels sprouts in a wide bowl.",
      "Top with peas, red onion, tomatoes, olives, and mozzarella.",
      "Mound the roast beef on top.",
      "Sprinkle with shaved cheese.",
      "Drizzle with dressing and toss to serve."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.garlicandzest.com/cold-roast-beef-salad/"
  },
  {
    "id": "creamy-feta-dressing",
    "title": "Creamy Feta Dressing",
    "category": "Salad",
    "timeMinutes": 5,
    "servings": "Not listed",
    "source": "themediterraneandish.com",
    "tags": [
      "wprm-recipe-container-55666",
      "dressing"
    ],
    "accent": "purple",
    "intro": "Imported from themediterraneandish.com.",
    "ingredients": [
      "For the dressing:",
      "1/2 cup plain Greek yogurt",
      "6 oz feta cheese",
      "juice of 1 lemon",
      "3 tbsp extra virgin olive oil",
      "1 clove garlic, grated",
      "up to 1/2 cup water"
    ],
    "steps": [
      "Add the yogurt, feta, lemon juice, olive oil, grated garlic, and 2-3 tbsp water to a blender or food processor.",
      "Blend until creamy and pourable.",
      "Add more water, 1 tbsp at a time, until the dressing reaches the consistency you like.",
      "Store in a tightly closed jar in the refrigerator for up to 4 days.",
      "If it thickens in the fridge, whisk in a little water before serving."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.themediterraneandish.com/feta-dressing/#wprm-recipe-container-55666"
  },
  {
    "id": "creamy-pesto-chicken-and-vegetables",
    "title": "Creamy Pesto Chicken and Vegetables",
    "category": "Sauce",
    "timeMinutes": 20,
    "servings": "Not listed",
    "source": "themediterraneandish.com",
    "tags": [
      "wprm-recipe-container-35988",
      "bowl",
      "chicken",
      "pesto",
      "sauce"
    ],
    "accent": "red",
    "intro": "Imported from themediterraneandish.com.",
    "ingredients": [
      "For the chicken:",
      "1 1/2 lb chicken breast cutlets",
      "kosher salt",
      "black pepper",
      "extra virgin olive oil",
      "For the vegetables and sauce:",
      "1 zucchini, sliced into half moons",
      "1 red bell pepper, sliced",
      "1/2 red onion, sliced",
      "1 cup grape tomatoes",
      "1/3 cup pesto",
      "1/3 cup cream",
      "1 lemon, zested and juiced",
      "toasted pine nuts",
      "fresh basil"
    ],
    "steps": [
      "Pat the chicken dry and season both sides with salt and pepper.",
      "Heat about 2 tbsp olive oil in a large skillet over medium-high heat.",
      "Sear the chicken for 2-3 minutes per side, then transfer it to a plate.",
      "Add a little more oil if the skillet looks dry.",
      "Add the zucchini, bell pepper, red onion, and tomatoes.",
      "Season with salt and pepper and cook, tossing now and then, until softened, about 6-7 minutes.",
      "Mix the pesto and cream in a small bowl.",
      "Return the chicken to the skillet and pour in the pesto cream.",
      "Lower the heat to medium-low and cook until the chicken is warmed through, about 1 minute.",
      "Take the skillet off the heat.",
      "Finish with lemon zest and about half the lemon juice.",
      "Taste and add more lemon juice, salt, or pepper if needed.",
      "Garnish with toasted pine nuts and fresh basil if using."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.themediterraneandish.com/pesto-chicken-recipe/#wprm-recipe-container-35988"
  },
  {
    "id": "crispy-chicken-with-caesar-salad",
    "title": "Crispy Chicken with Caesar Salad",
    "category": "Salad",
    "timeMinutes": 30,
    "servings": "Not listed",
    "source": "frederikkewaerens.dk",
    "tags": [
      "bowl",
      "caesar",
      "chicken",
      "dressing",
      "salad"
    ],
    "accent": "green",
    "intro": "Imported from frederikkewaerens.dk.",
    "ingredients": [
      "For the crispy chicken:",
      "4 chicken breasts",
      "3 eggs",
      "150 g cornflakes",
      "250 g wheat flour",
      "1 tsp salt",
      "pepper",
      "1 tsp garlic powder",
      "1 tsp paprika",
      "oil for frying",
      "For the Caesar salad:",
      "200 g sour cream or creme fraiche",
      "1-2 tsp mustard",
      "1 garlic clove, pressed",
      "75 g Parmesan, grated",
      "1/2 tsp sugar",
      "1 tsp salt",
      "pepper",
      "lemon juice",
      "2 romaine lettuces",
      "Extras:",
      "grated Parmesan"
    ],
    "steps": [
      "Pound the chicken breasts flatter between two sheets of baking paper.",
      "Whisk the eggs in one bowl.",
      "Crush the cornflakes into another bowl.",
      "In a third bowl, mix the flour, salt, pepper, garlic powder, and paprika.",
      "Coat each chicken breast in the flour mixture, then egg, then crushed cornflakes.",
      "Add enough oil to cover the bottom of a deep frying pan and heat it.",
      "Fry the chicken for about 3-4 minutes on each side, until golden and cooked through.",
      "Drain on a rack or paper towel and sprinkle with salt.",
      "Mix the sour cream, mustard, garlic, and Parmesan.",
      "Season the dressing with sugar, salt, pepper, and lemon juice.",
      "Slice the romaine and toss with the dressing.",
      "Serve the crispy chicken topped with Caesar salad and grated Parmesan."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://frederikkewaerens.dk/en/crispy-chicken-with-caesar-salad/"
  },
  {
    "id": "crispy-smashed-potato-salad",
    "title": "Crispy Smashed Potato Salad",
    "category": "Baking",
    "timeMinutes": 1,
    "servings": "Not listed",
    "source": "hungryhappens.net",
    "tags": [
      "dressing",
      "potato",
      "salad"
    ],
    "accent": "tomato",
    "intro": "Imported from hungryhappens.net.",
    "ingredients": [
      "For the potatoes:",
      "2 lb baby potatoes, scrubbed",
      "1 tbsp olive oil",
      "salt",
      "pepper",
      "For the salad:",
      "3/4 cup Greek yogurt",
      "1/2 cup kewpie mayo",
      "2 tsp Dijon mustard",
      "juice of 1/2 large lemon",
      "2 tsp red wine vinegar",
      "1 large garlic clove, minced",
      "1/4 cup fresh dill, chopped",
      "1/4 cup fresh parsley, chopped",
      "1 medium cucumber, seeded and finely chopped",
      "1 shallot, finely chopped"
    ],
    "steps": [
      "Heat the oven to 425 F and line a large baking sheet with parchment.",
      "Boil the potatoes until fork tender, about 7 minutes.",
      "Dry the potatoes and move them to the baking sheet.",
      "Smash each potato flat with the bottom of a glass.",
      "Brush with olive oil and season with salt and pepper.",
      "Roast for 50-60 minutes, until golden and crisp.",
      "Save a few crispy potato bits for garnish.",
      "While the potatoes roast, whisk together the yogurt, mayo, Dijon, lemon juice, vinegar, garlic, dill, parsley, salt, and pepper.",
      "Stir in the cucumber and shallot.",
      "Cover and refrigerate the dressing while the potatoes finish.",
      "Let the potatoes cool for 5 minutes.",
      "Fold the potatoes into the dressing until coated.",
      "Garnish with the crispy potato bits, dill, and black pepper."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://hungryhappens.net/crispy-smashed-potato-salad/"
  },
  {
    "id": "currywurst-goulash",
    "title": "Currywurst Goulash",
    "category": "Sauce",
    "timeMinutes": 300,
    "servings": "Not listed",
    "source": "instagram.com",
    "tags": [
      "goulash",
      "sauce",
      "vegetable"
    ],
    "accent": "yellow",
    "intro": "Imported from instagram.com.",
    "ingredients": [
      "For the goulash:",
      "2 tbsp cooking oil, for frying the sausages",
      "500 g cooked bratwurst",
      "1 tbsp cooking oil, for the vegetables",
      "120 g onions",
      "300 g bell peppers",
      "2 tbsp tomato paste",
      "3 tbsp curry powder",
      "1 tsp paprika powder",
      "1 tsp smoked paprika powder",
      "2 tbsp brown sugar",
      "300 ml cola",
      "500 ml passata",
      "50 g ketchup",
      "2 tbsp Worcestershire sauce",
      "2 tbsp apple cider vinegar",
      "1 tsp salt",
      "1 tsp onion powder",
      "1/2 tsp pepper",
      "To serve:",
      "bread"
    ],
    "steps": [
      "Slice the cooked bratwurst.",
      "Slice the onions and bell peppers.",
      "Heat 2 tbsp cooking oil in a deep pot.",
      "Add the sausages and fry until nicely browned.",
      "Remove the sausages and set aside.",
      "Add 1 tbsp more oil to the pot.",
      "Fry the onions and bell peppers until soft.",
      "Add the tomato paste, curry powder, paprika powder, smoked paprika powder, and brown sugar.",
      "Mix well.",
      "Add the cola and stir again.",
      "Once the mixture briefly comes to a boil, add the passata, ketchup, Worcestershire sauce, and apple cider vinegar.",
      "Season with salt, pepper, and onion powder.",
      "Mix everything well and simmer for about 5 minutes.",
      "Add the sausages back to the pot.",
      "Serve with bread on the side."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.instagram.com/p/DTU-WydDbGy/"
  },
  {
    "id": "gluten-free-beef-empanadas",
    "title": "Gluten Free Beef Empanadas",
    "category": "Dinner",
    "timeMinutes": 125,
    "servings": "Not listed",
    "source": "schaer.com",
    "tags": [
      "beef",
      "bowl"
    ],
    "accent": "blue",
    "intro": "Imported from schaer.com.",
    "ingredients": [
      "For the dough:",
      "125 ml hot water",
      "180 g Mix Bread",
      "40 g butter",
      "For the filling:",
      "500 g ground beef",
      "2 tbsp olive oil",
      "2 shallots, chopped",
      "1 tsp paprika powder, sweet",
      "1 tsp cayenne pepper",
      "1 tbsp oregano",
      "salt",
      "black pepper",
      "green olives",
      "1 handful sultanas"
    ],
    "steps": [
      "Put the flour and butter in a bowl and pour the hot water over it.",
      "Mix everything with your hands until the ingredients are all incorporated.",
      "The dough becomes smooth and easy to work with.",
      "Take pieces of dough and spread with a rolling pin until very thin.",
      "Afterwards, cut with a cutter.",
      "When adding the filling, pass the rolling pin over it again, lightly, to spread the dough a little bit further.",
      "Put the filling and close the dough (if you do not know how to crimp the borders, just press with a fork, to close tightly).",
      "Put the olive oil and onion in a pan. Cook.",
      "Add the meat, stirring well, until all the meat is cooked.",
      "Add the paprika (dissolved in 1/4 of water), the Cayenne pepper, oregano, salt and black pepper.",
      "Let simmer for about 10 minutes.",
      "Turn off the flame and add the olives (if you prefer, chopped).",
      "If you prefer them whole, set aside to use when putting it all together, along with the raisins, if you like, and a chopped hard-boiled egg.",
      "Mix everything and let cool.",
      "Put the cold filling on the dough already spread out. Brush with 1 whisked egg. Bake in a pre-heated oven at 180°C until golden brown."
    ],
    "notes": [
      "Prepare the dough:",
      "Prepare the filling:"
    ],
    "sourceUrl": "https://www.schaer.com/en-int/r/beef-empanadas"
  },
  {
    "id": "gochujang-beef-with-sauteed-vegetables",
    "title": "Gochujang Beef with Sauteed Vegetables",
    "category": "Sauce",
    "timeMinutes": 3,
    "servings": "Not listed",
    "source": "triedandtruerecipe.com",
    "tags": [
      "beef",
      "bowl",
      "rice",
      "sauce",
      "vegetable"
    ],
    "accent": "purple",
    "intro": "Imported from triedandtruerecipe.com.",
    "ingredients": [
      "For the gochujang beef:",
      "3 tbsp gochujang",
      "3 tbsp brown sugar",
      "4 tbsp soy sauce",
      "1 tbsp sesame oil",
      "2 tsp chili oil",
      "1 lb boneless ribeye, sirloin, or skirt steak, thinly sliced against the grain",
      "1/2 yellow onion, thinly sliced",
      "3 scallions, thinly sliced on a diagonal",
      "salt",
      "pepper",
      "For the rice and vegetables:",
      "1 cup uncooked white rice",
      "3 scallions, whites and greens separated",
      "1 tsp sesame oil",
      "1 tsp sesame seeds",
      "2 tsp gochugaru",
      "2 tsp neutral oil",
      "1/2 yellow onion, thinly sliced",
      "3 medium carrots, sliced thickly on a diagonal",
      "5 oz baby spinach",
      "salt",
      "pepper"
    ],
    "steps": [
      "Mix the gochujang, brown sugar, soy sauce, sesame oil, and chili oil until smooth.",
      "Pat the beef dry and season lightly with salt and pepper.",
      "Toss the beef with the marinade, sliced onion, and scallions.",
      "Refrigerate for at least 30 minutes or up to overnight.",
      "Cook the rice according to the package and keep warm.",
      "Thinly slice the white scallion parts and slice the green parts on a diagonal.",
      "Toss the green scallion parts with 1 tsp sesame oil, sesame seeds, and gochugaru.",
      "Heat 2 tsp neutral oil in a large skillet over high heat until very hot.",
      "Add the beef and marinade in an even layer.",
      "Cook for 5-7 minutes, turning occasionally, until the beef is nearly cooked.",
      "Transfer the beef to a bowl, leaving extra marinade in the skillet.",
      "Return the skillet to medium-high heat.",
      "Add the onion, carrots, and white scallion parts.",
      "Cook for 8-10 minutes, tossing with the marinade left in the pan, until softened.",
      "Add a splash of water and the spinach.",
      "Cook 2-3 minutes, until the spinach wilts.",
      "Season with salt and pepper if needed.",
      "Serve the beef and vegetables over rice.",
      "Top with the dressed scallion greens."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.triedandtruerecipe.com/spicy-gochujang-beef-and-rice-with-sauteed-vegetables/"
  },
  {
    "id": "greek-sheet-pan-chicken",
    "title": "Greek Sheet-Pan Chicken",
    "category": "Baking",
    "timeMinutes": 1,
    "servings": "Not listed",
    "source": "themediterraneandish.com",
    "tags": [
      "wprm-recipe-container-69568",
      "chicken",
      "dressing",
      "vegetable",
      "zucchini"
    ],
    "accent": "red",
    "intro": "Imported from themediterraneandish.com.",
    "ingredients": [
      "For the ladolemono:",
      "1/4 cup fresh lemon juice, from about 2 large lemons",
      "1-2 tsp dried oregano",
      "1 large garlic clove, minced",
      "3/4 tsp kosher salt",
      "3/4 tsp black pepper",
      "3/4 cup extra virgin olive oil",
      "For the chicken and vegetables:",
      "1 large red onion, halved and sliced into 1/2-inch pieces",
      "1 medium zucchini, halved and sliced into 1/2-inch half moons",
      "1 large orange bell pepper, sliced 1/2-inch thick",
      "1 large tomato, cut into 8 wedges",
      "kosher salt",
      "ground black pepper",
      "6-8 boneless skinless chicken thighs",
      "1/4 cup pitted Kalamata olives",
      "1/4 cup pitted Castelvetrano olives",
      "4 oz feta cheese, cut into chunks",
      "1/4 cup chopped Italian parsley, for garnish"
    ],
    "steps": [
      "Heat the oven to 425 F with a rack in the middle.",
      "Whisk the lemon juice, oregano, garlic, salt, and pepper.",
      "Slowly drizzle in the olive oil while whisking until emulsified.",
      "Spread the onion, zucchini, bell pepper, and tomato on a large sheet pan.",
      "Season with salt and pepper.",
      "Pour about 1/4 cup dressing over the vegetables and toss.",
      "Season the chicken on both sides with salt and pepper.",
      "Nestle the chicken, olives, and feta among the vegetables.",
      "Drizzle with the remaining dressing, making sure the chicken is coated.",
      "Bake until the chicken is cooked through, about 35 minutes.",
      "Broil briefly for more color if desired.",
      "Spoon the pan juices over the chicken.",
      "Garnish with parsley and serve."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.themediterraneandish.com/greek-sheet-pan-chicken/#wprm-recipe-container-69568"
  },
  {
    "id": "ground-beef-and-cabbage-skillet",
    "title": "Ground Beef and Cabbage Skillet",
    "category": "Dinner",
    "timeMinutes": 30,
    "servings": "Not listed",
    "source": "themediterraneandish.com",
    "tags": [
      "beef",
      "cabbage",
      "vegetable"
    ],
    "accent": "green",
    "intro": "Imported from themediterraneandish.com.",
    "ingredients": [
      "For the skillet:",
      "1 large yellow onion",
      "4 tbsp extra virgin olive oil, divided",
      "2 garlic cloves, minced",
      "1 lb lean ground beef",
      "1 tsp cumin, divided",
      "1/2 tsp baharat",
      "1/2 tsp coriander",
      "1/4 tsp paprika",
      "kosher salt",
      "freshly ground black pepper",
      "1 small green cabbage, cored and shredded",
      "3 carrots, shredded",
      "1 tsp white wine vinegar",
      "2 scallions, trimmed and chopped",
      "3 tbsp chopped parsley"
    ],
    "steps": [
      "Halve the onion.",
      "Finely chop one half for the beef and thinly slice the other half for the vegetables.",
      "Heat 2 tbsp olive oil in a large heavy pan with a lid over medium-high heat.",
      "Add the chopped onion and cook until soft and fragrant, about 3-5 minutes.",
      "Add the garlic and cook for 30 seconds.",
      "Add the ground beef and break it up as it browns, about 7-10 minutes.",
      "Drain excess fat or liquid if needed.",
      "Season the beef with 1/2 tsp cumin, baharat, coriander, paprika, and a generous pinch each of salt and pepper.",
      "Transfer the beef to a plate.",
      "Heat the remaining 2 tbsp olive oil in the same pan over medium-high heat.",
      "Add the sliced onion, cabbage, carrots, remaining 1/2 tsp cumin, salt, and pepper.",
      "Toss well, cover, and steam for 3-5 minutes to wilt the cabbage.",
      "Uncover and cook, stirring occasionally, until the vegetables are tender and caramelized in places, about 15 minutes.",
      "Return the beef to the pan and toss to combine.",
      "Cook for 1-2 minutes, just until warmed through.",
      "Remove from the heat and stir in the vinegar, scallions, and parsley.",
      "Taste and finish with a drizzle of olive oil if desired."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.themediterraneandish.com/ground-beef-and-cabbage-skillet/"
  },
  {
    "id": "homemade-caesar-salad-dressing",
    "title": "Homemade Caesar Salad Dressing",
    "category": "Salad",
    "timeMinutes": 10,
    "servings": "Not listed",
    "source": "onceuponachef.com",
    "tags": [
      "bowl",
      "caesar",
      "dressing",
      "salad",
      "sauce"
    ],
    "accent": "tomato",
    "intro": "Imported from onceuponachef.com.",
    "ingredients": [
      "For the dressing:",
      "2 small garlic cloves, minced",
      "1 tsp anchovy paste",
      "2 tbsp freshly squeezed lemon juice",
      "1 tsp Dijon mustard",
      "1 tsp Worcestershire sauce",
      "1 cup mayonnaise",
      "1/2 cup freshly grated Parmigiano-Reggiano",
      "1/4 tsp salt",
      "1/4 tsp freshly ground black pepper"
    ],
    "steps": [
      "Whisk together the garlic, anchovy paste, lemon juice, Dijon mustard, and Worcestershire sauce in a medium bowl.",
      "Add the mayonnaise, Parmigiano-Reggiano, salt, and pepper.",
      "Whisk until smooth and well combined.",
      "Taste and adjust seasoning if needed.",
      "Refrigerate covered; it keeps well for about 1 week."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.onceuponachef.com/recipes/caesar-salad-dressing.html#recipe"
  },
  {
    "id": "indian-spiced-green-pea-soup",
    "title": "Indian-Spiced Green Pea Soup",
    "category": "Soup",
    "timeMinutes": 1,
    "servings": "Not listed",
    "source": "foodandspice.com",
    "tags": [
      "sauce",
      "soup",
      "vegetable"
    ],
    "accent": "yellow",
    "intro": "Imported from foodandspice.com.",
    "ingredients": [
      "For the soup:",
      "1 1/2 cups green or yellow split peas, or a combination",
      "2 tbsp olive oil",
      "1 small onion, diced",
      "1 celery stalk, sliced",
      "1 medium carrot, diced or thinly sliced",
      "4 whole cloves",
      "2 black cardamom pods, slightly crushed",
      "2 green or red chilies, seeded and finely chopped",
      "1-inch fresh ginger, minced or grated",
      "1 tbsp ground coriander",
      "2 tsp ground cumin",
      "1/2 tsp ground turmeric",
      "1/2 tsp Kashmiri or other chili powder",
      "1/4 tsp ground cayenne",
      "1/2 tsp amchoor powder, optional",
      "2 medium tomatoes, chopped",
      "5-6 cups vegetable stock or water, as needed",
      "1 1/2 cups frozen or fresh green peas",
      "1 tbsp fresh mint, chopped",
      "1 1/2 tsp sea salt, or to taste",
      "fresh cracked black pepper",
      "yogurt or cream, optional",
      "fresh mint leaves, optional"
    ],
    "steps": [
      "Rinse the split peas and soak for 6 hours or overnight.",
      "Drain, rinse, and set aside.",
      "Heat the olive oil in a large saucepan over medium heat.",
      "Add the onion, celery, and carrot and cook for about 5 minutes.",
      "Stir in the cloves, cardamom, chilies, ginger, coriander, cumin, turmeric, chili powder, cayenne, and amchoor if using.",
      "Cook for 1 minute.",
      "Add the split peas, tomatoes, and vegetable stock.",
      "Bring to a boil, reduce the heat, cover, and simmer until the split peas are tender, about 1 1/2 hours.",
      "Add the green peas and mint and simmer for about 5 minutes.",
      "Remove the cloves and cardamom pods.",
      "Season with salt and pepper.",
      "Partially puree the soup with an immersion blender or in batches.",
      "Serve hot or warm with yogurt or cream and fresh mint if desired."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.foodandspice.com/2022/05/indian-spiced-green-pea-soup.html"
  },
  {
    "id": "korean-zucchini-fritters",
    "title": "Korean Zucchini Fritters",
    "category": "Vegetarian",
    "timeMinutes": 2,
    "servings": "Not listed",
    "source": "christieathome.com",
    "tags": [
      "bowl",
      "potato",
      "rice",
      "sauce",
      "vegetable"
    ],
    "accent": "blue",
    "intro": "Imported from christieathome.com.",
    "ingredients": [
      "For the fritters:",
      "2 medium zucchini, about 7 inches long each",
      "2 large eggs",
      "1 tsp salt",
      "1/2 tsp toasted sesame oil",
      "1/4 cup potato starch, cornstarch, or all-purpose flour",
      "2 tbsp vegetable oil or neutral oil",
      "For the dipping sauce:",
      "2 tbsp regular soy sauce, tamari, or coconut aminos",
      "2 tbsp rice vinegar, white vinegar, or apple cider vinegar",
      "1 tbsp sesame oil",
      "1 tsp sesame seeds",
      "1/2 tsp gochugaru, red pepper flakes, or sliced chilis"
    ],
    "steps": [
      "Slice the zucchini into 1/4-inch rounds and discard the ends.",
      "Arrange the slices in a single layer.",
      "Sprinkle salt evenly over both sides and let sit for 10 minutes.",
      "Pat the zucchini dry with a paper towel.",
      "Coat each slice in potato starch or flour, shaking off excess.",
      "Lay the coated slices on a parchment-lined tray.",
      "Beat the eggs with the sesame oil in a small bowl.",
      "Heat 1 tbsp oil in a large pan over medium heat.",
      "Dip zucchini slices in the egg and add them to the pan in batches.",
      "Fry for 2-3 minutes per side, until golden.",
      "Drain on a rack or paper towel.",
      "Mix the dipping sauce ingredients in a small bowl.",
      "Serve the fritters with the sauce."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://christieathome.com/blog/korean-zucchini-fritters/"
  },
  {
    "id": "mediterranean-beef-bowls",
    "title": "Mediterranean Beef Bowls",
    "category": "Salad",
    "timeMinutes": 20,
    "servings": "Not listed",
    "source": "themediterraneandish.com",
    "tags": [
      "wprm-recipe-container-106335",
      "beef",
      "bowl",
      "dressing",
      "sauce"
    ],
    "accent": "purple",
    "intro": "Imported from themediterraneandish.com.",
    "ingredients": [
      "For the harissa oil:",
      "2 tbsp extra virgin olive oil",
      "2 tbsp harissa paste",
      "1 tsp Aleppo pepper flakes",
      "For the beef:",
      "1/4 cup extra virgin olive oil",
      "1 large yellow onion, finely chopped",
      "3 large garlic cloves, finely chopped",
      "1 large green bell pepper, diced",
      "kosher salt",
      "freshly ground black pepper",
      "3 tbsp tomato paste",
      "1/4 cup water",
      "1 1/2 lb lean ground beef",
      "1 1/2 tsp baharat",
      "1/2 tsp smoked Spanish paprika",
      "To serve:",
      "3 Roma tomatoes, diced",
      "3 Persian cucumbers, diced",
      "kosher salt",
      "extra virgin olive oil",
      "3 radishes, sliced",
      "1/2 cup chopped fresh cilantro or parsley",
      "pitted Castelvetrano or kalamata olives",
      "2 cups cooked whole grains, warmed",
      "tahini sauce or creamy feta dressing"
    ],
    "steps": [
      "Warm 2 tbsp olive oil in a small skillet over medium heat.",
      "Stir in the harissa paste and Aleppo pepper flakes, then set the harissa oil aside.",
      "Heat 1/4 cup olive oil in a large nonstick pan over medium-high heat.",
      "Add the onion, garlic, and bell pepper.",
      "Season with salt and pepper and cook until softened and fragrant, about 5 minutes.",
      "Stir in the tomato paste and water.",
      "Add the ground beef with another pinch of salt.",
      "Break up the meat and cook until browned, about 5-7 minutes.",
      "Drain excess fat if needed.",
      "Stir in the baharat and smoked paprika and cook a few minutes more, until the beef is fully cooked.",
      "Taste and adjust seasoning, then remove from the heat.",
      "Toss the tomatoes and cucumbers with a pinch of salt and a drizzle of olive oil.",
      "Divide the warm grains among bowls.",
      "Top with the beef, harissa oil, tahini sauce or feta dressing, tomato-cucumber mixture, radishes, herbs, and olives."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.themediterraneandish.com/mediterranean-beef-bowl/#wprm-recipe-container-106335"
  },
  {
    "id": "mediterranean-white-bean-soup-with-spinach-and-fresh-herbs",
    "title": "Mediterranean White Bean Soup with Spinach and Fresh Herbs",
    "category": "Soup",
    "timeMinutes": 1,
    "servings": "Not listed",
    "source": "themediterraneandish.com",
    "tags": [
      "wprm-recipe-container-79330",
      "bean",
      "soup",
      "vegetable"
    ],
    "accent": "red",
    "intro": "Imported from themediterraneandish.com.",
    "ingredients": [
      "For the soup:",
      "1 bunch parsley",
      "3 tbsp extra virgin olive oil",
      "1 medium yellow onion, finely chopped",
      "3 large garlic cloves, minced",
      "2 tbsp tomato paste",
      "2 large carrots, chopped",
      "2 celery stalks, chopped",
      "1 tsp Italian seasoning",
      "1 tsp sweet paprika",
      "1/2 tsp red pepper flakes or Aleppo pepper, plus more for serving",
      "kosher salt",
      "black pepper",
      "4 cups vegetable broth",
      "2 cans cannellini beans, drained and rinsed",
      "2 heaping cups spinach",
      "1/4 cup chopped fresh dill, stems removed",
      "2 tbsp white wine vinegar"
    ],
    "steps": [
      "Trim the parsley stem ends, then separate the leaves from the stems.",
      "Finely chop the stems and leaves separately.",
      "Heat the olive oil in a large Dutch oven over medium-high heat.",
      "Add the onion and garlic and cook until fragrant, about 3-5 minutes.",
      "Stir in the tomato paste, carrots, celery, and chopped parsley stems.",
      "Season with Italian seasoning, paprika, Aleppo pepper, salt, and black pepper.",
      "Cook until the vegetables soften slightly, about 5 minutes.",
      "Add the broth and beans.",
      "Bring to a boil and boil for about 5 minutes.",
      "Lower the heat, partially cover, and simmer until the beans and vegetables are very soft, about 20 minutes.",
      "Partially blend the soup if you want a creamier texture.",
      "Stir in the spinach, cover, and let it wilt for 1-2 minutes.",
      "Stir in the parsley leaves, dill, and white wine vinegar.",
      "Serve with a drizzle of olive oil and more Aleppo pepper if desired."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.themediterraneandish.com/white-bean-soup/#wprm-recipe-container-79330"
  },
  {
    "id": "mongolian-chicken",
    "title": "Mongolian Chicken",
    "category": "Sauce",
    "timeMinutes": 25,
    "servings": "Not listed",
    "source": "christieathome.com",
    "tags": [
      "chicken",
      "potato",
      "sauce",
      "vegetable"
    ],
    "accent": "green",
    "intro": "Imported from christieathome.com.",
    "ingredients": [
      "For the chicken:",
      "1 lb skinless boneless chicken thighs",
      "1/4 cup cornstarch or potato starch, plus more if needed",
      "1/3 cup vegetable oil or neutral oil",
      "For the sauce:",
      "2 garlic cloves, minced",
      "1 red chili pepper, sliced, optional",
      "5 slices ginger",
      "4 tbsp hoisin sauce",
      "2 tbsp regular soy sauce or light soy sauce",
      "2 tbsp brown sugar",
      "2 tsp sesame oil",
      "For the slurry:",
      "1 tbsp cornstarch or potato starch",
      "1/2 cup cold water",
      "Optional garnishes:",
      "1 green onion, finely chopped",
      "1 red chili pepper, sliced"
    ],
    "steps": [
      "Whisk the slurry ingredients together and set aside.",
      "Cut the chicken thighs into 1.5-inch cubes.",
      "Toss the chicken with the cornstarch until evenly coated.",
      "Heat the vegetable oil in a large pan over medium-high heat.",
      "Fry the chicken in batches until crispy, golden, and cooked through, about 5-7 minutes.",
      "Drain the chicken on a rack or paper towel.",
      "Pour off the excess oil, leaving about 2 tsp in the pan.",
      "Lower the heat to medium and stir-fry the ginger, garlic, and chili for about 10 seconds.",
      "Add the hoisin sauce, soy sauce, brown sugar, and sesame oil.",
      "Stir the slurry again, pour it in, and simmer until the sauce thickens.",
      "Add the chicken and toss until coated.",
      "Remove from the heat and garnish with green onion and chili if using."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://christieathome.com/blog/mongolian-chicken/"
  },
  {
    "id": "moroccan-fish-kofta-in-harissa-sauce",
    "title": "Moroccan Fish Kofta in Harissa Sauce",
    "category": "Baking",
    "timeMinutes": 45,
    "servings": "Not listed",
    "source": "themediterraneandish.com",
    "tags": [
      "wprm-recipe-container-79597",
      "bowl",
      "fish",
      "kofta",
      "sauce"
    ],
    "accent": "tomato",
    "intro": "Imported from themediterraneandish.com.",
    "ingredients": [
      "For the sauce:",
      "2 tbsp extra virgin olive oil",
      "3 large garlic cloves, minced",
      "1 15-oz can diced tomatoes with juices",
      "1 cup vegetable broth",
      "2 tbsp harissa paste",
      "1 large red bell pepper, thinly sliced",
      "1/2 packed cup chopped cilantro or parsley, plus more for garnish",
      "1/2 tsp ras el hanout",
      "1/2 tsp cumin",
      "1/2 lemon, finely chopped with peel and pith, seeds discarded",
      "kosher salt",
      "black pepper",
      "For the fish kofta:",
      "1 lb white fish fillet, such as halibut or cod, cut into large pieces",
      "1 small yellow onion, quartered",
      "2 garlic cloves",
      "1/2 packed cup fresh cilantro",
      "1/2 packed cup fresh parsley",
      "1 small hot chili pepper or jalapeno, stemmed, optional",
      "1 tsp ras el hanout",
      "1/2 tsp ground ginger",
      "1/2 tsp ground cinnamon",
      "kosher salt",
      "black pepper",
      "1/2 cup dried breadcrumbs",
      "1 egg, lightly whisked",
      "1/2 tbsp extra virgin olive oil"
    ],
    "steps": [
      "Heat the olive oil in a large pan with a lid.",
      "Add the garlic and cook over medium heat for about 30 seconds.",
      "Add the tomatoes, broth, harissa, and bell pepper.",
      "Stir in the herbs, ras el hanout, cumin, chopped lemon, salt, and pepper.",
      "Bring to a boil, then lower the heat and partially cover.",
      "Simmer gently while you make the fish balls.",
      "In a food processor, pulse the fish, onion, garlic, cilantro, parsley, chili if using, ras el hanout, ginger, cinnamon, salt, and pepper until blended.",
      "Transfer to a bowl.",
      "Mix in the breadcrumbs, egg, and olive oil.",
      "Form into small balls, about 1 tbsp each.",
      "Nestle the fish balls into the sauce and spoon sauce over the top.",
      "Partially cover and cook, turning gently now and then, until the fish is cooked through, about 10-15 minutes.",
      "Garnish with more cilantro or parsley and serve."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.themediterraneandish.com/moroccan-fish-kofta/#wprm-recipe-container-79597"
  },
  {
    "id": "potato-pie-with-leeks",
    "title": "Potato pie with leeks",
    "category": "Baking",
    "timeMinutes": 60,
    "servings": "Not listed",
    "source": "frederikkewaerens.dk",
    "tags": [
      "potato"
    ],
    "accent": "yellow",
    "intro": "Imported from frederikkewaerens.dk.",
    "ingredients": [
      "For the tart:",
      "700 g potatoes",
      "20 g butter",
      "1 leek",
      "200 g diced bacon",
      "1 onion, diced",
      "5 eggs",
      "3 tbsp crème fraîche",
      "75 g grated cheese",
      "salt",
      "pepper",
      "chives for garnish"
    ],
    "steps": [
      "Preheat the oven to 200°C fan.",
      "Boil the potatoes until tender in salted water.",
      "Brush a 23 cm springform pan with melted butter.",
      "Place the boiled potatoes in the pan and mash them well into the bottom and up the sides.",
      "Pre-bake the potato base for 15 minutes.",
      "Rinse the leek and cut it into thin slices.",
      "Pour boiling water over the leek and let it stand for 3 minutes.",
      "Drain the water and pat the leek dry.",
      "Fry the diced bacon in a pan.",
      "Add the onion just before the bacon is completely crisp.",
      "Transfer the bacon and onion onto kitchen paper.",
      "Whisk together the eggs, crème fraîche, grated cheese, salt, and pepper.",
      "Spread the leek and the bacon-onion mixture over the potato base.",
      "Pour the egg mixture over it.",
      "Bake the tart for about 20 minutes.",
      "Garnish with chives, carefully remove the springform pan, and serve."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://frederikkewaerens.dk/kartoffeltaerte-med-porre/"
  },
  {
    "id": "sheet-pan-chicken-kebab-wrap",
    "title": "Sheet Pan Chicken Kebab Wrap",
    "category": "Salad",
    "timeMinutes": 35,
    "servings": "Not listed",
    "source": "instagram.com",
    "tags": [
      "bowl",
      "chicken",
      "kebab",
      "salad",
      "sauce"
    ],
    "accent": "blue",
    "intro": "Imported from instagram.com.",
    "ingredients": [
      "For the kebabs:",
      "2 lb boneless skinless chicken thighs, minced",
      "salt, to taste",
      "1 yellow onion, very finely chopped and excess moisture squeezed out",
      "1 red bell pepper, very finely chopped and excess moisture squeezed out",
      "2 tbsp fresh parsley, chopped",
      "1 tbsp fresh garlic, finely minced",
      "1 tbsp smoked paprika powder",
      "1 tsp garlic powder",
      "1 tsp red chili flakes, adjust to taste",
      "1/2 tsp black pepper powder",
      "1 tsp ground cumin",
      "1/2 tsp ground coriander",
      "For the salad:",
      "1 cup yellow onion, diced",
      "1 cup tomatoes, seeded and diced",
      "1 red bell pepper, seeded and diced",
      "1 cup cucumber, diced",
      "1/2 red onion, sliced",
      "1 tbsp fresh parsley, chopped",
      "juice of 1 lemon",
      "1-2 tbsp pomegranate molasses",
      "salt, to taste",
      "2 tbsp extra virgin olive oil",
      "1 tsp sumac",
      "For the garlic yogurt sauce:",
      "1/2 cup mayonnaise",
      "2 tbsp sour cream",
      "2 tbsp Greek yogurt",
      "salt, to taste",
      "1 tbsp smoked paprika powder",
      "1/2 tsp black pepper powder",
      "2 tsp garlic powder",
      "lemon juice, to taste",
      "To assemble:",
      "6 lavash breads"
    ],
    "steps": [
      "Preheat the oven to 220 C.",
      "Grease a sheet pan with oil.",
      "In a mixing bowl, combine the minced chicken thighs, onion, red bell pepper, parsley, garlic, smoked paprika, garlic powder, red chili flakes, black pepper, cumin, coriander, and salt.",
      "Mix until evenly combined.",
      "Transfer the mixture to the sheet pan and press into an even layer, about 1/2 inch thick, divided into kebabs.",
      "Drizzle additional oil or butter on top.",
      "Bake on the bottom rack for 10-12 minutes.",
      "Broil on the top rack on high for 2 minutes.",
      "Flip and broil for another 2 minutes, or until lightly golden.",
      "In a bowl, combine the yellow onion, tomatoes, red bell pepper, cucumber, sliced red onion, and parsley.",
      "Add the lemon juice, pomegranate molasses, olive oil, sumac, and salt.",
      "Mix to combine.",
      "In another bowl, whisk together the mayonnaise, sour cream, Greek yogurt, garlic powder, smoked paprika, black pepper, lemon juice, and salt until smooth.",
      "Spread garlic yogurt sauce over each lavash.",
      "Top with sliced chicken kebab and fresh salad.",
      "Roll tightly.",
      "Warm in a skillet for 2-3 minutes, until golden and crispy."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.instagram.com/p/DU4AkRjjy30/?hl=en"
  },
  {
    "id": "shogayaki-japanese-ginger-pork-chops",
    "title": "Shogayaki Japanese Ginger Pork Chops",
    "category": "Sauce",
    "timeMinutes": 70,
    "servings": "Not listed",
    "source": "norecipes.com",
    "tags": [
      "bowl",
      "pork",
      "potato",
      "sauce",
      "vegetable"
    ],
    "accent": "purple",
    "intro": "Imported from norecipes.com.",
    "ingredients": [
      "For the pork:",
      "400 g pork rib chops, about 3/4-inch thick",
      "30 g ginger, peeled and grated",
      "1/4 tsp salt",
      "1 tbsp potato starch",
      "1 tbsp vegetable oil",
      "chopped scallions, for garnish",
      "For the sauce:",
      "2 tbsp sake",
      "2 tbsp soy sauce",
      "1 tbsp honey"
    ],
    "steps": [
      "Rub the grated ginger and salt onto both sides of the pork chops.",
      "Cover and refrigerate for at least 1 hour.",
      "Mix the sake, soy sauce, and honey in a small bowl.",
      "Pat the pork dry and scrape off large clumps of ginger.",
      "Dust both sides with a thin layer of potato starch.",
      "Heat a frying pan over medium heat.",
      "Add the oil and pork chops.",
      "Fry until the first side starts to brown, about 2 minutes.",
      "Flip and brown the second side, about 2 minutes.",
      "Flip the chops back over and wipe excess oil from the pan.",
      "Turn the heat to high and pour in the sauce.",
      "Flip the chops repeatedly in the boiling sauce until coated in a thick, shiny glaze.",
      "Serve whole or rest briefly before slicing.",
      "Garnish with scallions."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://norecipes.com/shogayaki-japanese-ginger-pork/#recipe"
  },
  {
    "id": "spiced-turkey-meatballs",
    "title": "Spiced Turkey Meatballs",
    "category": "Sauce",
    "timeMinutes": 60,
    "servings": "Not listed",
    "source": "realfood.tesco.com",
    "tags": [
      "bowl",
      "meatball",
      "sauce",
      "turkey"
    ],
    "accent": "red",
    "intro": "Imported from realfood.tesco.com.",
    "ingredients": [
      "For the meatballs and sauce:",
      "2 tbsp olive oil",
      "2 red onions, finely chopped",
      "1 tbsp coriander seeds, lightly crushed",
      "1 tbsp fennel seeds, crushed",
      "2 tsp ground cumin",
      "1 tsp smoked paprika",
      "1 large garlic clove, crushed",
      "2 400 g tins chopped tomatoes",
      "500 g turkey thigh mince",
      "1 egg, lightly beaten",
      "1 slice white bread, about 50 g, blitzed to crumbs",
      "10 g fresh flat-leaf parsley, chopped, optional"
    ],
    "steps": [
      "Heat 1 tbsp oil in a lidded frying pan over medium heat.",
      "Fry the onions for about 10 minutes, until softened.",
      "Stir in the coriander seeds, fennel seeds, cumin, and smoked paprika.",
      "Cook for 2 minutes.",
      "Spoon half the onion mixture into a bowl.",
      "Add the garlic to the pan and cook for 1 minute.",
      "Stir in the chopped tomatoes and simmer for 10 minutes.",
      "Tip the tomato sauce into a separate bowl and set aside.",
      "Add the turkey mince, egg, and breadcrumbs to the bowl with the reserved onion mixture.",
      "Beat with a wooden spoon until smooth.",
      "Shape into 18 meatballs, about 35 g each.",
      "Wipe the pan clean and heat the remaining oil over medium-high heat.",
      "Fry the meatballs for 8-10 minutes, turning often, until golden.",
      "Pour over the tomato sauce, cover, and cook for about 10 minutes, until cooked through.",
      "Finish with parsley and black pepper if using."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://realfood.tesco.com/recipes/spiced-turkey-meatballs.html"
  },
  {
    "id": "spicy-cauliflower-shawarma",
    "title": "Spicy Cauliflower Shawarma",
    "category": "Salad",
    "timeMinutes": 55,
    "servings": "Not listed",
    "source": "themediterraneandish.com",
    "tags": [
      "bowl",
      "cauliflower",
      "salad",
      "sauce",
      "shawarma"
    ],
    "accent": "green",
    "intro": "Imported from themediterraneandish.com.",
    "ingredients": [
      "For the cauliflower shawarma:",
      "1 large head cauliflower, divided into florets",
      "1 large yellow onion, halved and sliced",
      "2 tbsp shawarma spice blend",
      "kosher salt",
      "ground black pepper",
      "extra virgin olive oil",
      "To serve:",
      "pita bread",
      "3-ingredient Mediterranean salad",
      "tahini sauce",
      "1 red onion, thinly sliced, or pickled red onion",
      "cucumber pickles, optional"
    ],
    "steps": [
      "Heat the oven to 450 F.",
      "Put the cauliflower and onion in a large bowl.",
      "Toss with shawarma spice, a large pinch of salt, black pepper, and 2-3 tbsp olive oil.",
      "Spread the vegetables in a single layer on a large sheet pan.",
      "Cover the pan with foil.",
      "Bake on the center rack for about 15 minutes.",
      "Remove the foil.",
      "Continue roasting for 25-30 minutes, turning the cauliflower occasionally, until tender and caramelized in places.",
      "While the vegetables roast, prepare the salad and tahini sauce.",
      "Serve the cauliflower in pita with salad, red onion, pickles if using, and tahini sauce."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.themediterraneandish.com/cauliflower-shawarma/"
  },
  {
    "id": "spicy-salmon-rice-muffins",
    "title": "Spicy Salmon Rice Muffins",
    "category": "Baking",
    "timeMinutes": 30,
    "servings": "Not listed",
    "source": "hungryhappens.net",
    "tags": [
      "rice",
      "salmon",
      "sauce"
    ],
    "accent": "tomato",
    "intro": "Imported from hungryhappens.net.",
    "ingredients": [
      "For the muffins:",
      "3 sheets nori paper",
      "1 1/2 cups cooked sushi rice, cooled",
      "For the salmon:",
      "1 lb salmon, skin removed and cut into small cubes",
      "2 tbsp sesame oil or olive oil",
      "1 tbsp low-sodium soy sauce",
      "1 tbsp honey",
      "2 scallions, diced",
      "1/2 tsp garlic powder",
      "1/2 tsp onion powder",
      "1/2 tsp chili powder",
      "1/2 tsp paprika",
      "1/2 tsp dried oregano",
      "salt, to taste",
      "For the spicy mayo:",
      "1/4 cup kewpie mayo",
      "2 tsp sriracha",
      "1 tsp honey",
      "Toppings:",
      "1/2 avocado, diced small",
      "2 tsp black sesame seeds"
    ],
    "steps": [
      "Heat the oven to 400 F.",
      "Cut each nori sheet into 4 equal squares.",
      "Toss the salmon with sesame oil, soy sauce, honey, scallions, spices, and salt.",
      "Marinate for up to 4 hours if time allows.",
      "Put about 1 heaping tbsp rice onto each nori square and spread slightly.",
      "Press each square into a muffin cup so the rice sits in the middle and the nori edges come up the sides.",
      "Fill each cup with 4-5 salmon cubes.",
      "Bake for 15-17 minutes.",
      "Broil for 1-2 minutes if the salmon needs a little color.",
      "Mix the kewpie mayo, sriracha, and honey.",
      "Let the muffins cool slightly, then top with avocado, sesame seeds, and spicy mayo."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://hungryhappens.net/spicy-salmon-rice-muffins/#recipe"
  },
  {
    "id": "swedish-meatball-subs",
    "title": "Swedish Meatball Subs",
    "category": "Sauce",
    "timeMinutes": 50,
    "servings": "Not listed",
    "source": "tasty.co",
    "tags": [
      "beef",
      "meatball",
      "pork",
      "sauce"
    ],
    "accent": "yellow",
    "intro": "Imported from tasty.co.",
    "ingredients": [
      "For the meatballs:",
      "6 oz beef mince",
      "6 oz pork mince",
      "1 egg",
      "1 tbsp dill, finely chopped",
      "1 onion, finely diced",
      "1/2 cup breadcrumbs",
      "1 tsp salt",
      "1 tsp pepper",
      "For the sauce:",
      "1/8 cup water",
      "1 beef stock cube",
      "7/8 cup double cream",
      "2 tsp Dijon mustard",
      "2 tsp Worcestershire sauce",
      "To serve:",
      "3 soft French sticks",
      "1 cucumber, thinly sliced",
      "1 cup cranberry jam or lingonberry jam"
    ],
    "steps": [
      "Mix all the meatball ingredients thoroughly.",
      "Shape into golf ball-sized meatballs.",
      "Fry the meatballs over low to medium heat, turning to brown all sides, until cooked through, about 12-15 minutes.",
      "For the sauce, dissolve the beef stock cube in the water.",
      "Add the cream, Dijon mustard, and Worcestershire sauce.",
      "Pour the sauce into the pan with the meatballs.",
      "Toss the meatballs as the sauce reduces until thick and creamy.",
      "Serve in soft French sticks with cucumber slices and cranberry or lingonberry jam."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://tasty.co/recipe/swedish-meatball-subs"
  },
  {
    "id": "sweet-and-sour-pork",
    "title": "Sweet and Sour Pork",
    "category": "Sauce",
    "timeMinutes": 45,
    "servings": "Not listed",
    "source": "madewithlau.com",
    "tags": [
      "pork",
      "sauce"
    ],
    "accent": "blue",
    "intro": "Imported from madewithlau.com.",
    "ingredients": [
      "Main ingredients:",
      "10 oz pork shoulder butt",
      "1 oz red bell pepper",
      "1 oz yellow bell pepper",
      "1 oz green bell pepper",
      "1 oz red onion",
      "1 oz yellow onion",
      "4 oz pineapple",
      "1/2 lb corn oil, for frying",
      "For the pork marinade:",
      "1 tsp garlic salt",
      "1 tbsp light soy sauce",
      "1/2 egg, beaten",
      "2 tbsp all-purpose flour",
      "3 tbsp cornstarch",
      "For the sauce:",
      "4 tbsp ketchup",
      "4 tbsp brown sugar",
      "3 tbsp vinegar",
      "1 tsp cornstarch",
      "1/2 tsp salt",
      "2 tbsp water"
    ],
    "steps": [
      "Cut the pork into bite-sized pieces, slicing against the grain.",
      "Mix the pork with garlic salt and light soy sauce for about 1 minute.",
      "Add the beaten egg and mix again, then let the pork marinate while you prep the rest.",
      "Cut the bell peppers, onions, and pineapple into bite-sized pieces.",
      "Mix the ketchup, brown sugar, vinegar, cornstarch, salt, and water until smooth.",
      "Add the flour to the marinated pork and massage it in until evenly coated.",
      "Put the cornstarch on a plate and coat each pork piece, pressing so the starch sticks.",
      "Heat enough corn oil in a wok or deep pan to submerge the pork.",
      "Fry the pork at 300-350 F for 7-8 minutes, leaving it undisturbed for the first 1-2 minutes so the coating sets.",
      "Remove the pork and let it drain.",
      "Increase the oil temperature and fry the pork a second time until crisp and golden.",
      "Pour out the frying oil, leaving a little oil in the wok.",
      "Stir-fry the onions, bell peppers, and pineapple briefly.",
      "Add the sauce and cook until it thickens.",
      "Return the pork to the wok and toss quickly to coat.",
      "Serve right away while the pork is crisp."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.madewithlau.com/recipes/sweet-sour-pork"
  },
  {
    "id": "the-best-potato-salad",
    "title": "The Best Potato Salad",
    "category": "Salad",
    "timeMinutes": 25,
    "servings": "Not listed",
    "source": "instagram.com",
    "tags": [
      "bowl",
      "dressing",
      "potato",
      "salad"
    ],
    "accent": "purple",
    "intro": "Imported from instagram.com.",
    "ingredients": [
      "For the salad:",
      "2 potatoes",
      "4 soft-boiled eggs, 1 reserved for topping",
      "1/2 cucumber",
      "bacon, to taste",
      "salt, for the cucumber",
      "For the dressing:",
      "2 tbsp Greek yogurt",
      "2 tbsp mayonnaise",
      "1 tbsp mustard",
      "2 tbsp milk",
      "black pepper"
    ],
    "steps": [
      "Wrap the potatoes in plastic wrap and microwave at 600 W for 4-6 minutes, until softened.",
      "Use kitchen paper to rub off and remove the potato skins.",
      "Put enough water in a pot to fully cover 4 eggs.",
      "Bring the water to a boil.",
      "Carefully add the eggs and cook for 6 minutes.",
      "Transfer the eggs to ice water and leave for 5-10 minutes.",
      "Peel the eggs.",
      "Slice the cucumber thinly.",
      "Add a little salt to the cucumber and leave for about 5 minutes.",
      "Squeeze out the excess water from the cucumber.",
      "Cut the bacon and cook it in a pan until crispy.",
      "In a bowl, mix the Greek yogurt, mayonnaise, mustard, milk, and black pepper.",
      "Add 3 soft-boiled eggs, the potatoes, cucumber, and crispy bacon to the dressing bowl.",
      "Smash the potatoes and eggs gently.",
      "Fold everything together.",
      "Top with the reserved soft-boiled egg and sprinkle with black pepper."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.instagram.com/p/DYMpcvxRrCh/"
  },
  {
    "id": "tomato-chicken-and-couscous",
    "title": "Tomato Chicken and Couscous",
    "category": "Dinner",
    "timeMinutes": 1,
    "servings": "Not listed",
    "source": "themediterraneandish.com",
    "tags": [
      "chicken",
      "vegetable"
    ],
    "accent": "red",
    "intro": "Imported from themediterraneandish.com.",
    "ingredients": [
      "For the dish:",
      "2 bell peppers, red and yellow, chopped",
      "1 red onion, chopped",
      "1 celery stalk, chopped",
      "1 carrot, chopped",
      "1 medium leek, trimmed, halved lengthwise, and sliced into 1/2-inch half moons",
      "8 oz cherry tomatoes, quartered",
      "4 garlic cloves, minced",
      "2 tbsp extra virgin olive oil",
      "kosher salt",
      "freshly ground pepper",
      "6 large bone-in, skin-on chicken thighs",
      "1 tsp baharat spice",
      "1 tsp turmeric",
      "1 tbsp tomato paste",
      "2 cups pearl couscous",
      "2 cups vegetable broth or chicken broth",
      "1 large lemon, zested and juiced",
      "1 small bunch tarragon, finely chopped"
    ],
    "steps": [
      "Heat the oven to 400 F.",
      "In a large baking dish, combine the bell peppers, onion, celery, carrot, leek, tomatoes, garlic, olive oil, salt, and pepper.",
      "Pat the chicken dry.",
      "Season the chicken all over with salt, pepper, baharat, and turmeric.",
      "Nestle the chicken into the vegetables, skin side down.",
      "Roast uncovered for 30 minutes.",
      "Transfer the chicken to a plate.",
      "Stir the tomato paste, couscous, broth, lemon zest, lemon juice, and most of the tarragon into the baking dish.",
      "Place the chicken on top, skin side up, keeping the skin exposed.",
      "Roast until the couscous absorbs most of the liquid and the chicken skin is crisp, about 30 minutes.",
      "Garnish with the reserved tarragon and serve."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.themediterraneandish.com/tomato-chicken-thighs-and-couscous/"
  },
  {
    "id": "recipe-9a414206",
    "title": "Грузинский суп из фасоли с овощами и рисом",
    "category": "Dinner",
    "timeMinutes": 600,
    "servings": "Not listed",
    "source": "gastronom.ru",
    "tags": [
      "recipe"
    ],
    "accent": "green",
    "intro": "Imported from gastronom.ru.",
    "ingredients": [
      "Для супа:",
      "300 г сухой белой фасоли",
      "2 средние луковицы",
      "1 средняя морковка",
      "1 крупный помидор",
      "100 г круглого риса",
      "1 средний пучок петрушки",
      "1 средний пучок кинзы",
      "5-7 зубчиков чеснока",
      "топленое масло",
      "1 лавровый лист",
      "аджика",
      "соль"
    ],
    "steps": [
      "Замочите фасоль в холодной воде на 8-10 часов.",
      "Слейте воду, промойте фасоль и залейте 2 л свежей воды.",
      "Поставьте на сильный огонь, доведите до кипения, снимите пену, уменьшите огонь и варите до разваривания фасоли, 1-1,5 часа.",
      "Выньте шумовкой горсть фасоли, разомните ее в пюре и верните обратно в кастрюлю.",
      "Промойте рис, всыпьте его в кастрюлю с фасолью и варите, пока рис не разварится, 20-25 минут.",
      "Очистите и мелко нарежьте лук.",
      "Очистите морковь и натрите на крупной терке.",
      "Обжарьте лук на топленом масле до золотистого цвета.",
      "Добавьте морковь и потушите на слабом огне 5 минут.",
      "Срежьте с помидора крышечку, натрите его на терке, кожицу выбросьте.",
      "Добавьте помидор в сковородку и потушите 5 минут.",
      "Добавьте тушеные овощи в суп и варите 10 минут.",
      "Измельчите зелень и положите в суп.",
      "Очистите чеснок, растолките в ступке с солью.",
      "Добавьте чеснок в суп вместе с лавровым листом и аджикой по вкусу.",
      "Потомите еще 5 минут и подавайте.",
      "Суп становится еще вкуснее, если дать ему настояться несколько часов или ночь."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.gastronom.ru/recipe/43768/gruzinskij-sup-iz-fasoli-s-ovoshchami-i-risom"
  },
  {
    "id": "recipe-36877fc3",
    "title": "Запеченный суши-торт",
    "category": "Dinner",
    "timeMinutes": 90,
    "servings": "Not listed",
    "source": "instagram.com",
    "tags": [
      "recipe"
    ],
    "accent": "tomato",
    "intro": "Imported from instagram.com.",
    "ingredients": [
      "Для риса:",
      "250 г японского риса",
      "500 мл воды",
      "Для заправки риса:",
      "3 ст.л. рисового уксуса",
      "2,5 ст.л. сахара",
      "2 ч.л. соли",
      "Для начинки:",
      "200 г крабовых палочек",
      "150 г крем-сыра",
      "2 ст.л. майонеза",
      "Для шапочки:",
      "150 г твердого сыра",
      "1 банка икры мойвы с креветкой или лососем",
      "2 ст.л. майонеза",
      "Для подачи:",
      "соус унаги",
      "чипсы из нори"
    ],
    "steps": [
      "Тщательно промойте рис 3-4 раза, пока вода не станет прозрачной.",
      "Откиньте рис на дуршлаг и оставьте на 1 час.",
      "Переложите рис в кастрюлю, добавьте 500 мл воды и закройте крышкой.",
      "Варите 5 минут на сильном огне.",
      "Убавьте огонь до минимального и варите, пока не выпарится вся вода.",
      "Выключите огонь и оставьте рис под крышкой еще на 15 минут.",
      "Для заправки смешайте рисовый уксус, сахар и соль.",
      "Влейте заправку в рис и аккуратно перемешайте деревянной лопаткой.",
      "Дайте рису остыть.",
      "Нарежьте крабовые палочки и смешайте их с крем-сыром и майонезом.",
      "Для шапочки натрите твердый сыр и смешайте его с икрой мойвы и майонезом.",
      "Выложите рис в форму ровным слоем.",
      "Сверху распределите начинку из крабовых палочек.",
      "Накройте сырной шапочкой.",
      "Запекайте 20 минут при 180 C.",
      "Перед подачей добавьте соус унаги и чипсы из нори."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.instagram.com/p/DU3MFtOjCaU/"
  },
  {
    "id": "recipe-11fb580f",
    "title": "Паприкаш из свинины",
    "category": "Dinner",
    "timeMinutes": 30,
    "servings": "Not listed",
    "source": "iamcook.ru",
    "tags": [
      "recipe"
    ],
    "accent": "yellow",
    "intro": "Imported from iamcook.ru.",
    "ingredients": [
      "Для паприкаша:",
      "800 г мяса, свинина или другое",
      "2-4 помидора",
      "2 сладких перца",
      "1 головка лука",
      "150 мл сметаны или сливок",
      "около 1 ст.л. муки",
      "паприка хлопьями и/или молотая, по вкусу",
      "растительное масло для жарки",
      "соль по вкусу"
    ],
    "steps": [
      "Нарежьте мясо кусочками.",
      "Обжарьте мясо на растительном масле.",
      "Добавьте нашинкованный лук, обжарьте все вместе и потушите около 5 минут.",
      "Посолите, посыпьте мукой, перемешайте и немного потушите в собственном соку.",
      "Добавьте нарезанные помидоры, лучше без кожицы, и нашинкованный сладкий перец.",
      "В конце добавьте сметану или сливки.",
      "Перемешайте, оставьте на выключенной плите на несколько минут и дайте настояться.",
      "Подавайте с кнедлями, галушками, отварным картофелем, пюре, макаронами или крупами."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.iamcook.ru/showrecipe/3063"
  },
  {
    "id": "recipe-5ee42083",
    "title": "Цветная капуста в липком китайском соусе",
    "category": "Dinner",
    "timeMinutes": 40,
    "servings": "Not listed",
    "source": "gastronom.ru",
    "tags": [
      "recipe"
    ],
    "accent": "blue",
    "intro": "Imported from gastronom.ru.",
    "ingredients": [
      "Для капусты:",
      "0,5 среднего кочана цветной капусты",
      "0,5 стакана пшеничной муки",
      "1 стакан хлебной крошки",
      "0,5 ч.л. соли",
      "0,25 ч.л. черного перца",
      "Для соуса:",
      "0,3 стакана соевого соуса",
      "0,3 стакана соуса хойсин",
      "2 ст.л. меда",
      "1 ч.л. лимонного сока",
      "4 зубчика чеснока",
      "1 ч.л. тертого имбиря",
      "5 капель табаско",
      "100 мл воды",
      "Для гарнирования:",
      "кунжут",
      "зеленый лук"
    ],
    "steps": [
      "Разогрейте духовку до 200 градусов.",
      "Разложите по отдельным тарелкам муку, яйцо и хлебные сухари.",
      "Смешайте соль и черный перец с хлебной крошкой.",
      "Разберите цветную капусту на мелкие соцветия.",
      "Обваляйте соцветия в муке, затем в яйце, затем в хлебной крошке.",
      "Выложите капусту на противень с пергаментом.",
      "Выпекайте 15-20 минут, пока капуста не станет слегка хрустящей.",
      "Сложите все ингредиенты соуса в сотейник.",
      "Доведите до кипения на среднем огне и варите около 5 минут, пока соус не начнет густеть.",
      "Полейте запеченную капусту соусом и аккуратно перемешайте.",
      "Подавайте с кунжутом и зеленым луком."
    ],
    "notes": [
      "Imported from Markdown."
    ],
    "sourceUrl": "https://www.gastronom.ru/recipe/47126/cvetnaya-kapusta-v-lipkom-kitajskom-souse"
  }
];
